apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: imagetransform-deployment
  namespace: imwiz
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: imagetransform-deployment
  minReplicas: 3
  maxReplicas: 8 
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 
        #- type: Resource
        #resource:
        #name: memory 
        #target:
        #type: Utilization 
        #averageUtilization: 40
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 4
        periodSeconds: 15

