apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: imwiz
data:
  imwiz.conf: |
    proxy_cache_path /data/nginx/cache keys_zone=imwiz:10000m loader_threshold=300 loader_files=200 max_size=200m;
    #proxy_cache_path /var/cache/nginx/s3_proxy keys_zone=imwiz:10000m loader_threshold=300 loader_files=200 max_size=200m;

            server {
            root /var/www/html;
            listen 443 ssl http2 default_server;
            listen [::]:443 ssl http2 default_server;
            set $bypass $http_cache_purge;

            index index.html index.htm index.nginx-debian.html;
            server_name imwiztest.cloud-testing.io; 
            ssl_certificate /etc/nginx/certs/tls.crt;
            ssl_certificate_key /etc/nginx/certs/tls.key;

            location /transform {
              ##include proxy_params;
              proxy_pass http://imagetransform-service.imwiz.svc.cluster.local:8000;
              proxy_cache imwiz;
              #proxy_cache_key   $uri$is_args$args$slice_range$http_accept;
              proxy_cache_key   $uri$request_uri$args$slice_range$http_accept;
              proxy_set_header  Range $slice_range;
              proxy_cache_valid 200 206 1d;
              add_header X-Nginx-Cache $upstream_cache_status;
              proxy_cache_bypass $bypass;
              }

            location /healthcheck {
              proxy_pass http://imagetransform-service.imwiz.svc.cluster.local:8000;
            }
            }

              

