apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cache
  namespace: imwiz
spec:
  capacity:
    storage: 30Gi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/nginx/cache"
